[package]
name = "cairo1"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
cairo_lib = { git = "https://github.com/HerodotusDev/cairo-lib.git", rev = "93ebbac8997452255c9b12a13ad75dece577850f" }

[dev-dependencies]
cairo_test = "2.9.2"

[cairo]
sierra-replace-ids = true

enable-gas = false
