[package]
name = "zeroxbridge-sequencer"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.15.11"
serde = "1.0"
serde_json = "1.0.133"
anyhow = "1.0.95"
axum = "0.8.1"
tokio = { version = "1.44.1", features = ["full"] }
sqlx = { version = "0.8.3", features = [
  "postgres",
  "runtime-tokio-rustls",
  "macros",
  "migrate",
] }
starknet = "0.13.0"
tracing = "0.1.41"
chrono = "0.4.40"
thiserror = "2.0.12"
mockall = "0.13.1"

[package.metadata.sqlx]
offline = true
