[package]
name = "zeroxbridge-sequencer"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.15.11"
serde = "1.0"
serde_json = "1.0.133"
anyhow = "1.0.95"
axum = "0.8.1"
tokio = { version = "1.44.1", features = ["full"] }
sqlx-cli = "0.8.3"
tracing = "0.1.41"
sha2 = "0.10.8"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4.3"
dotenvy = "0.15"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http = { version = "0.6", features = ["trace"] }

